name: test
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gcc mandelbrot.c
      - run: sudo apt-get install texlive gnuplot-nox
      - run: gnuplot plot.gpi
      - run: pdflatex art.tex
      - uses: actions/upload-artifact@v4
        with:
          path: art.pdf
